spring:

  sql:
    init:
      mode: always

  datasource:
    url: jdbc:postgresql://localhost:5438/clients_data_base
    username: admin
    password: admin
    driverClassName: org.postgresql.Driver
    hikari:
      max-lifetime: 7200000
      maximum-pool-size: 10

  jpa:
    show-sql: true
    open-in-view: false
    defer-datasource-initialization: true
    hibernate:
      ddl-auto: create
    properties:
      hibernate:
        format_sql: true
        default_batch_fetch_size: 20
        jdbc.batch_size: 20

  jackson:
    visibility:
      field: any
      getter: none
      setter: none
      is-getter: none